### ISSUE TITLE
Warnings during binwalk -A

### ISSUE THREAD

**Issue by alex-bender** [devttys0/binwalk#151]
```
$ git clone https://github.com/devttys0/binwalk
$ cd  binwalk
$ sudo ./deps.sh
$ sudo python setup.py install
$ binwalk -A

WARNING: Error loading plugin 'compressd.py': /usr/local/lib/ctypes.so: undefined symbol: list_optarg
```

Warning repeated approx 20 times.

```
$ uname -a
Linux bender 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ python -V 
Python 2.7.9

```

**Comment by devttys0** [comment]
It sounds like an issue in `ctypes`, but I can't reproduce this error on my machine. The `compressd.py` plugin is not currently used though, so I've removed any code in `compressd.py` that could be responsible for invoking `ctypes`, which should fix this problem.

**Comment by alex-bender** [comment]
I have uninstalled binwalk and the installed it again, but error is still present.

**Comment by devttys0** [comment]
Nowhere does binwalk directly reference `list_optarg`, which leads me to believe there is something wrong with the `ctypes` Python interface. Can you start a Python shell and run `import ctypes` and `import ctypes.util` without errors/warnings?

**Comment by alex-bender** [comment]
Here it is:

```
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> import ctypes.util
```

**Comment by devttys0** [comment]
`compressd.py` in the latest master literally does nothing. See if this fixes your issue.

**Comment by alex-bender** [comment]
Yes, it is fixed. Thanks
```
$ binwalk -A
$ echo $?
0
```
